version: '2'
services:
    jhipster5-app:
        image: jhipster5
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipster5-postgresql:5432/jhipster5
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster5-postgresql:
        extends:
            file: postgresql.yml
            service: jhipster5-postgresql
